version: '{branch}-{build}'

build: off

skip_branch_with_pr: true

image:
  - Ubuntu2004
  - Visual Studio 2022
  - macos-monterey

platform:
# - x86
  - x64

#cache:
#  - pixel-change-test

for:
  -
    matrix:
      only:
        - image: Visual Studio 2022
#   init:
#     - ps: Get-Childitem -Path Env:* | Sort-Object Name
#     - ps: $env:OS
    install:
      - ps: Install-Product node lts
      - npm install
    before_build:
      - npm test
      - npm run clean
      - ps: if ($env:APPVEYOR_REPO_TAG -eq "false") { Exit-AppveyorBuild }
    build_script:
      - npm run prebuildify
#     - npm run prebuildify:ia32
    after_build:
#     - ps: Get-ChildItem -Force -Recurse .\prebuilds
      - ps: $env:ARCHIVE_NAME="$env:APPVEYOR_REPO_TAG_NAME-$env:OS-$env:PLATFORM.zip"
#     - ps: $env:ARCHIVE_NAME
      - ps: 7z a $env:ARCHIVE_NAME ./prebuilds/win32-x64
#     - ps: 7z a $env:ARCHIVE_NAME ./prebuilds/win32-x64 ./prebuilds/win32-ia32
      - ps: Push-AppveyorArtifact $env:ARCHIVE_NAME
    before_test:
      - node --version
      - npm --version
      - ps: Remove-Item -Recurse -Path ./build
    test_script:
      - npm test
  -
    matrix:
      only:
        - image: Ubuntu2004
#   init:
#     - env
#     - nvm ls-remote
#     - uname -s
    install:
      - nvm install --lts
      - npm install
    before_build:
      - npm test
      - npm run clean
      - if [[ "$APPVEYOR_REPO_TAG" == "false" ]]; then appveyor exit; fi
    build_script:
      - npm run prebuildify
    after_build:
#     - ls -lAR ./prebuilds
      - ARCHIVE_NAME="$APPVEYOR_REPO_TAG_NAME-$(uname -s)-$(uname -m).tar"
#     - echo $ARCHIVE_NAME
      - tar --create --verbose --file="$ARCHIVE_NAME" --directory "./prebuilds/" linux-x64
      - appveyor PushArtifact $ARCHIVE_NAME
    before_test:
      - node --version
      - npm --version
#      - rm -rf ./build
    test_script:
      - npm test
  -
    matrix:
      only:
        - image: macos-monterey
#   init:
#     - env
#     - nvm ls-remote
#     - uname -s
    install:
      - nvm install --lts
      - npm install
    before_build:
      - npm test
      - npm run clean
      - if [[ "$APPVEYOR_REPO_TAG" == "false" ]]; then appveyor exit; fi
    build_script:
      - npm run prebuildify
    after_build:
#     - ls -lAR ./prebuilds
      - ARCHIVE_NAME="$APPVEYOR_REPO_TAG_NAME-$(uname -s)-$(uname -m).tar"
#     - echo $ARCHIVE_NAME
      - tar --create --verbose --file="$ARCHIVE_NAME" --directory "./prebuilds" darwin-x64
      - appveyor PushArtifact $ARCHIVE_NAME
    before_test:
      - node --version
      - npm --version
#      - rm -rf ./build
    test_script:
      - npm test

deploy:
  - provider: GitHub
    draft: false
    prerelease: true
    force_update: true
    on:
      APPVEYOR_REPO_TAG: true
    auth_token:
      secure: AceIXxoZshw6mTg16yFH8IDPsUc1CtybbGfBC6e1AmBtwzIWvlI2asGj2uGVVz8K