build: off

skip_branch_with_pr: true

environment:
  matrix:
    - nodejs_version: "Current"

configuration: Release
platform:
  - x86
  - x64

install:
  - SET PATH=C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\bin;%PATH%
  - ps: Install-Product node $env:nodejs_version $env:platform
  - npm install

test_script:
  - node --version
  - npm --version
  - npm test

after_test:
  - ps: If ($env:nodejs_version -eq "Current" -AND $env:APPVEYOR_REPO_TAG -eq "true") { npm run prebuild }

#artifacts:
#  - path: prebuilds
#    name: $(APPVEYOR_REPO_TAG_NAME)-win-$(PLATFORM)
#    type: zip

#before_deploy:
#  - ps: echo "$($env:APPVEYOR_REPO_TAG_NAME)-win-$($env:PLATFORM)"
#  - ls -lR prebuilds
#  - ps: Push-AppveyorArtifact "prebuilds/*" -FileName "my-name" -Type zip

before_deploy:
#  - ps: echo $env:APPVEYOR_REPO_TAG
#  - ps: echo $(APPVEYOR_REPO_TAG)
#  - ps: echo $(APPVEYOR_REPO_TAG_NAME)-win-$(PLATFORM)
#  - ps: If ($env:APPVEYOR_REPO_TAG -eq "false" ) { echo "is false" }
#  - ps: If ($env:APPVEYOR_REPO_TAG -eq "true" ) { Push-AppveyorArtifact prebuilds -FileName $(APPVEYOR_REPO_TAG_NAME)-win-$(PLATFORM) -Type zip }
  - ps: If ($env:APPVEYOR_REPO_TAG -eq "true" ) { Push-AppveyorArtifact prebuilds -FileName $(APPVEYOR_REPO_TAG_NAME)-win-$(PLATFORM) -Type zip }

deploy:
  - provider: GitHub
    artifact: /.*\.zip/
    draft: false
    prerelease: true
    auth_token:
      secure: LmtUDSct7WXwF0+0q8Lm55Wi1A0SLsh+GMOIvu7XondTiBA6Z+TfBHLwhOY681/o
    on:
      APPVEYOR_REPO_TAG: true
      nodejs_version: "Current"
