build: off

skip_branch_with_pr: true

environment:
  matrix:
    - nodejs_version: "Current"

configuration: Release

platform:
  - x86
  - x64

image: Visual Studio 2017

install:
  - SET PATH=C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\bin;%PATH%
  - ps: Install-Product node $env:nodejs_version $env:platform
  - npm install
  - ps: $env:package_version = (Get-Content -Raw -Path package.json | ConvertFrom-Json).version
  - ps: Update-AppveyorBuild -Version "$env:package_version-$env:APPVEYOR_REPO_BRANCH-$env:APPVEYOR_BUILD_NUMBER"

test_script:
  - node --version
  - npm --version
  - npm test

before_deploy:
  - npm run prebuild
  - ps: $env:ARCHIVE_NAME = "$($env:APPVEYOR_REPO_TAG_NAME)-win-$($env:PLATFORM).zip"
  - ps: 7z a $env:ARCHIVE_NAME .\prebuilds\*
  - ps: Push-AppveyorArtifact $env:ARCHIVE_NAME

deploy:
  - provider: GitHub
    artifact: /.*\.zip/
    draft: false
    prerelease: true
    auth_token:
      secure: LmtUDSct7WXwF0+0q8Lm55Wi1A0SLsh+GMOIvu7XondTiBA6Z+TfBHLwhOY681/o
    on:
      APPVEYOR_REPO_TAG: true
      nodejs_version: "Current"